apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  postgres-user: cG9zdGdlc3VzZXI=
  postgres-password: cG9zdGdlc3Bhc3N3b3Jk
